apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: expense-service
      version: v1
  template:
    metadata:
      labels:
        app: expense-service
        version: v1
    spec:
      containers:
        - name: expense-service
          image: "raghultamilaiah/expense-service"
