apiVersion: v1
kind: Service
metadata:
  name: expense-service-defn
spec:
  type: LoadBalancer
  selector:
    app: expense-service
  ports:
  - name: http
    protocol: TCP
    port: 8085
    targetPort: 8080
    nodePort: 30007